### ISSUE TITLE
Updating SlopedPlanesMacro WB to be compatible with the upcoming 0.18 release (req. py3 and Qt5 compatibility)

### ISSUE THREAD

**Issue by luzpaz** [caceres/SlopedPlanesMacro#6]
ref: https://github.com/FreeCAD/FreeCAD-addons/issues/93

**Comment by luzpaz** [comment]
This is complete?

**Comment by caceres** [comment]
pyside2 complete

**Comment by caceres** [comment]
modifications in develop branch.
I'll update the master branch once more this year, in December. A lot of work!
